"""rename department

Revision ID: 767ad27e4502
Revises: 12a788da9ff3
Create Date: 2024-06-30 02:10:00.493935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767ad27e4502'
down_revision = '12a788da9ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###